# range(2, 11, 2): This creates a range object that starts at 2, ends before 11, and increments by 2. 
# The numbers generated by this range are 2, 4, 6, 8, and 10.
# The list() function is used to create a new list from the elements generated by the range.

even_numbers = list(range(2,11,2))

print(even_numbers)